//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.RecipeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipe", Namespace="http://schemas.datacontract.org/2004/07/WCFServices")]
    [System.SerializableAttribute()]
    public partial class Recipe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DislikesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IngredientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LikesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherdetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Dislikes {
            get {
                return this.DislikesField;
            }
            set {
                if ((this.DislikesField.Equals(value) != true)) {
                    this.DislikesField = value;
                    this.RaisePropertyChanged("Dislikes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ingredients {
            get {
                return this.IngredientsField;
            }
            set {
                if ((object.ReferenceEquals(this.IngredientsField, value) != true)) {
                    this.IngredientsField = value;
                    this.RaisePropertyChanged("Ingredients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Likes {
            get {
                return this.LikesField;
            }
            set {
                if ((this.LikesField.Equals(value) != true)) {
                    this.LikesField = value;
                    this.RaisePropertyChanged("Likes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Method {
            get {
                return this.MethodField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodField, value) != true)) {
                    this.MethodField = value;
                    this.RaisePropertyChanged("Method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Otherdetails {
            get {
                return this.OtherdetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherdetailsField, value) != true)) {
                    this.OtherdetailsField = value;
                    this.RaisePropertyChanged("Otherdetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RecipeServiceReference.IRecipeService")]
    public interface IRecipeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeService/GetAllRecipes", ReplyAction="http://tempuri.org/IRecipeService/GetAllRecipesResponse")]
        WebClient.RecipeServiceReference.Recipe[] GetAllRecipes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeService/GetAllRecipes", ReplyAction="http://tempuri.org/IRecipeService/GetAllRecipesResponse")]
        System.Threading.Tasks.Task<WebClient.RecipeServiceReference.Recipe[]> GetAllRecipesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeService/GetRecipe", ReplyAction="http://tempuri.org/IRecipeService/GetRecipeResponse")]
        WebClient.RecipeServiceReference.Recipe GetRecipe(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeService/GetRecipe", ReplyAction="http://tempuri.org/IRecipeService/GetRecipeResponse")]
        System.Threading.Tasks.Task<WebClient.RecipeServiceReference.Recipe> GetRecipeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeService/AddLike", ReplyAction="http://tempuri.org/IRecipeService/AddLikeResponse")]
        bool AddLike(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeService/AddLike", ReplyAction="http://tempuri.org/IRecipeService/AddLikeResponse")]
        System.Threading.Tasks.Task<bool> AddLikeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeService/AddDislike", ReplyAction="http://tempuri.org/IRecipeService/AddDislikeResponse")]
        bool AddDislike(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeService/AddDislike", ReplyAction="http://tempuri.org/IRecipeService/AddDislikeResponse")]
        System.Threading.Tasks.Task<bool> AddDislikeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeService/GetUserSpecificRecipes", ReplyAction="http://tempuri.org/IRecipeService/GetUserSpecificRecipesResponse")]
        WebClient.RecipeServiceReference.Recipe[] GetUserSpecificRecipes(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeService/GetUserSpecificRecipes", ReplyAction="http://tempuri.org/IRecipeService/GetUserSpecificRecipesResponse")]
        System.Threading.Tasks.Task<WebClient.RecipeServiceReference.Recipe[]> GetUserSpecificRecipesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeService/DeleteRecipe", ReplyAction="http://tempuri.org/IRecipeService/DeleteRecipeResponse")]
        bool DeleteRecipe(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecipeService/DeleteRecipe", ReplyAction="http://tempuri.org/IRecipeService/DeleteRecipeResponse")]
        System.Threading.Tasks.Task<bool> DeleteRecipeAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecipeServiceChannel : WebClient.RecipeServiceReference.IRecipeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecipeServiceClient : System.ServiceModel.ClientBase<WebClient.RecipeServiceReference.IRecipeService>, WebClient.RecipeServiceReference.IRecipeService {
        
        public RecipeServiceClient() {
        }
        
        public RecipeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecipeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebClient.RecipeServiceReference.Recipe[] GetAllRecipes() {
            return base.Channel.GetAllRecipes();
        }
        
        public System.Threading.Tasks.Task<WebClient.RecipeServiceReference.Recipe[]> GetAllRecipesAsync() {
            return base.Channel.GetAllRecipesAsync();
        }
        
        public WebClient.RecipeServiceReference.Recipe GetRecipe(int id) {
            return base.Channel.GetRecipe(id);
        }
        
        public System.Threading.Tasks.Task<WebClient.RecipeServiceReference.Recipe> GetRecipeAsync(int id) {
            return base.Channel.GetRecipeAsync(id);
        }
        
        public bool AddLike(int id) {
            return base.Channel.AddLike(id);
        }
        
        public System.Threading.Tasks.Task<bool> AddLikeAsync(int id) {
            return base.Channel.AddLikeAsync(id);
        }
        
        public bool AddDislike(int id) {
            return base.Channel.AddDislike(id);
        }
        
        public System.Threading.Tasks.Task<bool> AddDislikeAsync(int id) {
            return base.Channel.AddDislikeAsync(id);
        }
        
        public WebClient.RecipeServiceReference.Recipe[] GetUserSpecificRecipes(int id) {
            return base.Channel.GetUserSpecificRecipes(id);
        }
        
        public System.Threading.Tasks.Task<WebClient.RecipeServiceReference.Recipe[]> GetUserSpecificRecipesAsync(int id) {
            return base.Channel.GetUserSpecificRecipesAsync(id);
        }
        
        public bool DeleteRecipe(int id) {
            return base.Channel.DeleteRecipe(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteRecipeAsync(int id) {
            return base.Channel.DeleteRecipeAsync(id);
        }
    }
}
